-- Migration: v1.x (Supabase) → v2.0 (local SQLite)
--
-- v2.0 uses a new local SQLite database at ~/.claude_memory.db.
-- The schema is applied automatically by mem.py on first run —
-- no migration script needs to be executed for fresh installs.
--
-- To carry over memories from v1.x (Supabase):
--   1. Export your memories from Supabase as JSON
--      (Supabase Dashboard → Table Editor → Export to CSV/JSON)
--   2. For each memory record, run:
--        echo '<memory-json>' | python3 ~/mem.py store
--   3. Verify the import:
--        python3 ~/mem.py list
