-- Claude Memory Skill — Semantic Search (Future)
--
-- This file is reserved for a future local semantic search implementation
-- using on-device embedding models.
--
-- The current FTS5-based keyword search covers the primary use case.
-- Semantic search (finding memories by meaning even when keywords differ)
-- is planned for a future release and will use local embeddings to keep
-- all data on-device.
--
-- Track progress: https://github.com/ShibanBanerjee/claude-memory-skill/issues
